# Generated by Django 5.0.6 on 2026-07-14 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(max_length=15)),
                ('new_status', models.CharField(max_length=15)),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'booking_audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('player_phone', models.CharField(max_length=20)),
                ('player_count', models.PositiveSmallIntegerField(default=1)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('source', models.CharField(choices=[('online', 'Online'), ('offline_manual', 'Offline (Manual)')], default='online', max_length=15)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('no_show', 'No-Show')], default='confirmed', max_length=15)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash on Arrival'), ('bkash', 'bKash'), ('nagad', 'Nagad')], default='cash', max_length=10)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='unpaid', max_length=10)),
                ('amount', models.PositiveIntegerField(help_text='Total slot price in BDT')),
                ('platform_fee', models.PositiveIntegerField(help_text='Platform fee in BDT')),
                ('amount_paid', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=300)),
                ('created_by_owner', models.ForeignKey(blank=True, help_text='Set when owner marks an offline booking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings_created_as_owner', to=settings.AUTH_USER_MODEL)),
                ('created_by_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings_created_as_player', to=settings.AUTH_USER_MODEL)),
                ('player', models.ForeignKey(blank=True, help_text='Null for guest checkouts', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bookings',
                'ordering': ['-created_at'],
            },
        ),
    ]
