# Generated by Django 5.0.6 on 2026-07-14 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('turfs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='turf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='turfs.turf'),
        ),
        migrations.AddField(
            model_name='bookingauditlog',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='bookingauditlog',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['turf', 'date'], name='idx_booking_turf_date'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['player_phone'], name='idx_booking_player_phone'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='idx_booking_status'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'cancelled'), _negated=True), fields=('turf', 'date', 'start_time'), name='unique_active_booking_per_slot'),
        ),
    ]
