# Generated by Django 5.0.6 on 2026-07-14 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp')], max_length=10)),
                ('message_type', models.CharField(default='generic', max_length=50)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('stub', 'Stub (Dev)')], default='stub', max_length=10)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('error_message', models.TextField(blank=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='bookings.booking')),
            ],
            options={
                'db_table': 'notification_logs',
                'ordering': ['-sent_at'],
            },
        ),
    ]
