# Generated by Django 5.0.6 on 2026-07-14 09:02

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('address', models.TextField()),
                ('area', models.CharField(help_text='Area/neighbourhood in Rajshahi', max_length=100)),
                ('lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('sport_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('football', 'Football'), ('cricket', 'Cricket'), ('volleyball', 'Volleyball')], max_length=20), default=list, help_text='List of sports available at this turf', size=None)),
                ('amenities', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text="e.g. ['lights','changing_room','parking','water']", size=None)),
                ('base_price', models.PositiveIntegerField(help_text='Price per slot in BDT')),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('cancellation_hours', models.PositiveIntegerField(default=3, help_text='Free cancellation up to this many hours before slot start')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turfs', to='users.owner')),
            ],
            options={
                'db_table': 'turfs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SlotOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('blocked', 'Blocked / Maintenance'), ('special_price', 'Special Price')], default='blocked', max_length=15)),
                ('price', models.PositiveIntegerField(blank=True, help_text='Override price (only for special_price status)', null=True)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('turf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_overrides', to='turfs.turf')),
            ],
            options={
                'db_table': 'slot_overrides',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='TurfPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='turf_photos/')),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('turf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='turfs.turf')),
            ],
            options={
                'db_table': 'turf_photos',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='OperatingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('slot_duration_min', models.PositiveSmallIntegerField(default=90, help_text='Slot duration in minutes (default 90)')),
                ('is_closed', models.BooleanField(default=False, help_text='Mark this day as closed (no slots)')),
                ('turf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='turfs.turf')),
            ],
            options={
                'db_table': 'operating_schedules',
                'ordering': ['day_of_week'],
                'unique_together': {('turf', 'day_of_week')},
            },
        ),
    ]
